import 'dart:convert';
import 'package:flutter_application_1/model/user_model.dart';
import 'package:http/http.dart' as http;

class ApiService {
  fetchUsers() async {
    // final response =
    //     await http.get(Uri.parse('https://api.openweathermap.org/data/2.5/weather?lat=24.8607&lon=67.0011&appid=d32e8f6a3baa434890620250a16d9d08'));
    // var data = jsonDecode(response.body.toString());
    // if (response.statusCode == 200) {
    //   for (Map i in data){
    //     AutoGen.add(Autogenerated.fromJson(i));
    //   }
    //   return AutoGen;
    // } else {
    //   throw Exception('Failed to load Users');
    // }
  }
}